language: csharp
mono: none
dotnet: 2.2
solution: SDMOpgaver.sln

script:
 - dotnet restore
 - dotnet build
 - dotnet test SDMExercisesXunit/SDMExercisesXunit.csproj
 - dotnet test SDMBusExerciseTest/SDMBusExerciseTest.csproj